services:
  optics-agent:
    build: .
    image: optics-agent
    ports:
      - "${AGENT_PORT:-5230}:5230"
    volumes:
      - "./data.db:/app/data.db"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - service-network
    env_file: ./.env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  optics-agent-dashboard:
    build: ../OPTiCS-Agent-Dashboard
    image: optics-agent-dashboard
    ports:
      - "${DASHBOARD_PORT:-5240}:80"
    networks:
      - service-network

networks:
  service-network: {}
