// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from '@prisma/config';
import fs from 'fs';
import path from 'path';

function isContainerRuntime() {
  return process.env.OPTICS_AGENT_RUNTIME === 'container' || fs.existsSync('/.dockerenv');
}

function databaseUrl() {
  const configured = process.env.DATABASE_URL;
  if (isContainerRuntime()) {
    return configured ?? 'file:/app/data/data.db';
  }

  if (configured && configured !== 'file:/app/data/data.db') {
    return configured;
  }

  return `file:${path.resolve(process.cwd(), 'data', 'data.db')}`;
}

export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: databaseUrl(),
  },
});
