export enum COMMAND {
  DEPLOY = 'DEPLOY',
  REDEPLOY = 'REDEPLOY',
  ABORT = 'ABORT',
  START = 'START',
  STOP = 'STOP',
  DELETE = 'DELETE',
  DISCONNECT = 'DISCONNECT',
  STREAM_LOG = 'STREAM_LOG',
  STOP_LOG = 'STOP_LOG',
}